# Generated by Django 4.2.21 on 2025-05-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('예금', '예금'), ('적금', '적금'), ('금', '금'), ('은', '은'), ('주식', '주식')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=30, unique=True)),
                ('default_risk_level', models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggests.productcategory')),
            ],
        ),
    ]
