# Generated by Django 4.2.21 on 2025-05-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0002_productcategory_productriskcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentProfile',
        ),
    ]
