# Generated by Django 4.2.21 on 2025-05-26 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggests', '0004_stockrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_asset', models.PositiveIntegerField(help_text='추천 시점의 현재 자산')),
                ('target_asset', models.PositiveIntegerField(help_text='추천 시점의 목표 자산')),
                ('target_years', models.PositiveIntegerField(help_text='추천 시점의 남은 기간(년)')),
                ('required_return', models.FloatField(help_text='추천 시점 계산된 필요 수익률(%)')),
                ('total_score', models.IntegerField(help_text='추천 시점의 투자 성향 점수')),
                ('risk_type', models.CharField(help_text='추천 시점의 리스크 타입', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suggests.recommendation')),
            ],
        ),
    ]
