# Generated by Django 4.2.21 on 2025-05-27 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('risk_type', models.CharField(choices=[('안정형', '안정형'), ('안정추구형', '안정추구형'), ('위험중립형', '위험중립형'), ('적극투자형', '적극투자형'), ('공격투자형', '공격투자형')], max_length=20)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_asset', models.PositiveIntegerField(help_text='현재 자산 (만원)')),
                ('target_asset', models.PositiveIntegerField(help_text='목표 자산 (만원)')),
                ('target_years', models.PositiveIntegerField(help_text='목표까지 남은 기간 (년)')),
                ('expected_annual_return', models.FloatField(blank=True, help_text='필요 예상 수익률 (%)', null=True)),
                ('preferred_period', models.PositiveIntegerField(default=12, help_text='선호 투자 기간 (개월)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
