# Generated by Django 4.2.21 on 2025-05-27 05:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='current_asset',
            field=models.PositiveIntegerField(help_text='현재 자산 (만원)', validators=[django.core.validators.MinValueValidator(1, message='현재 자산은 1만원 이상이어야 합니다.'), django.core.validators.MaxValueValidator(1000000, message='현재 자산은 10억원(100만 만원) 이하여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='expected_annual_return',
            field=models.FloatField(blank=True, help_text='필요 예상 수익률 (%)', null=True, validators=[django.core.validators.MinValueValidator(-50, message='예상 수익률은 -50% 이상이어야 합니다.'), django.core.validators.MaxValueValidator(100, message='예상 수익률은 100% 이하여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='preferred_period',
            field=models.PositiveIntegerField(default=12, help_text='선호 투자 기간 (개월)', validators=[django.core.validators.MinValueValidator(1, message='선호 투자 기간은 1개월 이상이어야 합니다.'), django.core.validators.MaxValueValidator(360, message='선호 투자 기간은 360개월(30년) 이하여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='target_asset',
            field=models.PositiveIntegerField(help_text='목표 자산 (만원)', validators=[django.core.validators.MinValueValidator(1, message='목표 자산은 1만원 이상이어야 합니다.'), django.core.validators.MaxValueValidator(10000000, message='목표 자산은 100억원(1000만 만원) 이하여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='target_years',
            field=models.PositiveIntegerField(help_text='목표까지 남은 기간 (년)', validators=[django.core.validators.MinValueValidator(1, message='목표 기간은 1년 이상이어야 합니다.'), django.core.validators.MaxValueValidator(50, message='목표 기간은 50년 이하여야 합니다.')]),
        ),
    ]
