# Generated by Django 4.2.21 on 2025-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_name_short', models.CharField(max_length=100)),
                ('stock_name_en', models.CharField(max_length=100)),
                ('first_trade_date', models.DateField()),
                ('market', models.CharField(max_length=10)),
                ('security_type', models.CharField(max_length=10)),
                ('market_division', models.CharField(max_length=10)),
                ('stock_type', models.CharField(max_length=10)),
                ('face_value', models.IntegerField()),
                ('listed_shares', models.IntegerField()),
            ],
        ),
    ]
