# Generated by Django 4.2.21 on 2025-05-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_fin_grp_no', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=200)),
                ('kor_co_nm', models.CharField(max_length=200)),
                ('fin_prdt_cd', models.CharField(max_length=200)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=200, null=True)),
                ('mtrt_int', models.TextField(max_length=20000)),
                ('spcl_cnd', models.TextField(max_length=20000)),
                ('join_deny', models.CharField(max_length=200)),
                ('join_member', models.CharField(max_length=200)),
                ('etc_note', models.TextField(max_length=20000)),
                ('max_limit', models.BigIntegerField(null=True)),
                ('dcls_strt_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=200)),
                ('intr_rate_type_nm', models.CharField(max_length=200)),
                ('save_trm', models.CharField(max_length=200)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_fin_grp_no', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=200)),
                ('kor_co_nm', models.CharField(max_length=200)),
                ('fin_prdt_cd', models.CharField(max_length=200)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('join_way', models.CharField(max_length=200, null=True)),
                ('mtrt_int', models.TextField(max_length=20000)),
                ('spcl_cnd', models.TextField(max_length=20000)),
                ('join_deny', models.CharField(max_length=200)),
                ('join_member', models.CharField(max_length=200)),
                ('etc_note', models.TextField(max_length=20000)),
                ('max_limit', models.BigIntegerField(null=True)),
                ('dcls_strt_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_name_en', models.CharField(max_length=100)),
                ('first_trade_date', models.DateField()),
                ('market', models.CharField(max_length=50)),
                ('security_type', models.CharField(max_length=20)),
                ('market_division', models.CharField(max_length=20)),
                ('stock_type', models.CharField(max_length=20)),
                ('face_value', models.FloatField(blank=True, help_text='액면가 (무액면은 null)', null=True)),
                ('listed_shares', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=200)),
                ('intr_rate_type_nm', models.CharField(max_length=200)),
                ('rsrv_type_nm', models.CharField(max_length=200)),
                ('save_trm', models.CharField(max_length=200)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField()),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_products.savingproduct')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savingproduct',
            constraint=models.UniqueConstraint(fields=('fin_prdt_cd', 'fin_co_no'), name='unique_saving_product'),
        ),
        migrations.AddField(
            model_name='depositproductoptions',
            name='deposit_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_products.depositproduct'),
        ),
        migrations.AddConstraint(
            model_name='depositproduct',
            constraint=models.UniqueConstraint(fields=('fin_prdt_cd', 'fin_co_no'), name='unique_deposit_product'),
        ),
        migrations.AddConstraint(
            model_name='savingproductoptions',
            constraint=models.UniqueConstraint(fields=('fin_co_no', 'saving_product', 'intr_rate_type_nm', 'save_trm', 'rsrv_type_nm'), name='unique_option_saving'),
        ),
        migrations.AddConstraint(
            model_name='depositproductoptions',
            constraint=models.UniqueConstraint(fields=('fin_co_no', 'deposit_product', 'intr_rate_type_nm', 'save_trm'), name='unique_option_deposit'),
        ),
    ]
