# Generated by Django 4.2.21 on 2025-05-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggests', '0002_productcategory_productriskcategory'),
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suggests.productcategory'),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='risk_level',
            field=models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='category',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suggests.productcategory'),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='risk_level',
            field=models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suggests.productcategory'),
        ),
        migrations.AddField(
            model_name='stock',
            name='risk_level',
            field=models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], default='high', max_length=10),
        ),
    ]
