# Generated by Django 4.2.21 on 2025-05-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_name_short',
        ),
    ]
