# Generated by Django 4.2.21 on 2025-05-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0002_depositproduct_category_depositproduct_risk_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproductoptions',
            name='deposit_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositproductoptions', to='financial_products.depositproduct'),
        ),
        migrations.AlterField(
            model_name='savingproductoptions',
            name='saving_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savingproductoptions', to='financial_products.savingproduct'),
        ),
    ]
