# Generated by Django 4.2.21 on 2025-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0002_remove_stock_stock_name_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_division',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='security_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(max_length=20),
        ),
    ]
