# Generated by Django 4.2.21 on 2025-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0003_alter_stock_market_alter_stock_market_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='face_value',
            field=models.IntegerField(blank=True, help_text='액면가 (무액면은 null)', null=True),
        ),
    ]
