# Generated by Django 4.2.21 on 2025-05-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0003_alter_depositproductoptions_deposit_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=200, unique=True, verbose_name='예금 금융회사명')),
                ('top_fin_grp_no', models.CharField(max_length=100, verbose_name='금융회사 분류 코드')),
            ],
            options={
                'verbose_name': '예금 금융회사',
                'verbose_name_plural': '예금 금융회사 목록',
                'db_table': 'financial_products_depositcompany',
            },
        ),
        migrations.CreateModel(
            name='SavingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=200, unique=True, verbose_name='적금 금융회사명')),
                ('top_fin_grp_no', models.CharField(max_length=100, verbose_name='금융회사 분류 코드')),
            ],
            options={
                'verbose_name': '적금 금융회사',
                'verbose_name_plural': '적금 금융회사 목록',
                'db_table': 'financial_products_savingcompany',
            },
        ),
    ]
