# Generated by Django 4.2.21 on 2025-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0004_alter_stock_face_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='face_value',
            field=models.FloatField(blank=True, help_text='액면가 (무액면은 null)', null=True),
        ),
    ]
