# Generated by Django 4.2.21 on 2025-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0004_depositcompany_savingcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproduct',
            name='risk_level',
            field=models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], default='medium', max_length=10),
        ),
    ]
