# Generated by Django 4.2.21 on 2025-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0005_alter_stock_face_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='listed_shares',
            field=models.BigIntegerField(),
        ),
    ]
