# Generated by Django 4.2.21 on 2025-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0006_alter_stock_listed_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
