# Generated by Django 4.2.21 on 2025-05-25 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0007_alter_stock_stock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=100)),
                ('mtrt_int', models.TextField(max_length=2000)),
                ('spcl_cnd', models.TextField(max_length=2000)),
                ('join_deny', models.CharField(max_length=100)),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField(max_length=2000)),
                ('max_limit', models.BigIntegerField(null=True)),
                ('dcls_strt_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=100)),
                ('mtrt_int', models.TextField(max_length=2000)),
                ('spcl_cnd', models.TextField(max_length=2000)),
                ('join_deny', models.CharField(max_length=100)),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField(max_length=2000)),
                ('max_limit', models.BigIntegerField(null=True)),
                ('dcls_strt_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('rsrv_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_products.savingproduct', to_field='fin_prdt_cd')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_products.depositproduct', to_field='fin_prdt_cd')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savingproductoptions',
            constraint=models.UniqueConstraint(fields=('intr_rate_type_nm', 'save_trm'), name='unique_option_saving'),
        ),
        migrations.AddConstraint(
            model_name='depositproductoptions',
            constraint=models.UniqueConstraint(fields=('intr_rate_type_nm', 'save_trm'), name='unique_option_deposit'),
        ),
    ]
