# Generated by Django 4.2.21 on 2025-05-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0009_alter_depositproduct_etc_note_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depositproductoptions',
            name='unique_option_deposit',
        ),
        migrations.RemoveConstraint(
            model_name='savingproductoptions',
            name='unique_option_saving',
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='join_way',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_way',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='depositproductoptions',
            constraint=models.UniqueConstraint(fields=('deposit_product', 'intr_rate_type_nm', 'save_trm'), name='unique_option_deposit'),
        ),
        migrations.AddConstraint(
            model_name='savingproductoptions',
            constraint=models.UniqueConstraint(fields=('saving_product', 'intr_rate_type_nm', 'save_trm'), name='unique_option_saving'),
        ),
    ]
