# Generated by Django 4.2.21 on 2025-05-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0010_remove_depositproductoptions_unique_option_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositproductoptions',
            name='fin_prdt_cd',
        ),
        migrations.RemoveField(
            model_name='savingproductoptions',
            name='fin_prdt_cd',
        ),
    ]
