# Generated by Django 4.2.21 on 2025-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0011_remove_depositproductoptions_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproductoptions',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
    ]
