# Generated by Django 4.2.21 on 2025-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0012_alter_savingproductoptions_intr_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproductoptions',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
    ]
