# Generated by Django 4.2.21 on 2025-05-26 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_asset', models.PositiveIntegerField(help_text='현재 자산 (만원)')),
                ('target_asset', models.PositiveIntegerField(help_text='목표 자산 (만원)')),
                ('target_years', models.PositiveIntegerField(help_text='목표까지 남은 기간 (년)')),
                ('expected_annual_return', models.FloatField(blank=True, help_text='필요 예상 수익률 (%)', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
