# Generated by Django 4.2.21 on 2025-05-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investmentgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentgoal',
            name='preferred_period',
            field=models.PositiveIntegerField(default=12, help_text='선호 투자 기간 (개월)'),
        ),
    ]
