# Generated by Django 4.2.21 on 2025-05-26 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investmentgoal_preferred_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('risk_type', models.CharField(choices=[('안정형', '안정형'), ('안정추구형', '안정추구형'), ('위험중립형', '위험중립형'), ('적극투자형', '적극투자형'), ('공격투자형', '공격투자형')], max_length=20)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
